apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyle-uncensored
spec:
  selector:
    matchLabels:
      app: cyle-uncensored
  replicas: 1
  template:
    metadata:
      labels:
        app: cyle-uncensored
    spec:
      containers:
      - name: cyle-uncensored
        image: harbor.dotglitch.dev/library/cyle-uncensored:latest
      imagePullSecrets:
      - name: harbor-key
      env:
        - name: webhookKey
          valueFrom:
            secretKeyRef:
              name: cyle-uncensored-secret
              key: webhookKey       
        - name: token
          valueFrom:
            secretKeyRef:
              name: cyle-uncensored-secret
              key: token