apiVersion: apps/v1
kind: Deployment
metadata:
  name: uncensored
spec:
  selector:
    matchLabels:
      app: uncensored
  replicas: 1
  template:
    metadata:
      labels:
        app: uncensored
    spec:
      containers:
      - name: uncensored
        image: harbor.dotglitch.dev/library/uncensored:latest
        env:
          - name: webhookKey
            valueFrom:
              secretKeyRef:
                name: uncensored-secret
                key: webhookKey       
          - name: token
            valueFrom:
              secretKeyRef:
                name: uncensored-secret
                key: token
      imagePullSecrets:
      - name: harbor-key
